language: go

env:
  matrix:
    - _GOOS=windows _GOARCH=386
    - _GOOS=windows _GOARCH=amd64
    - _GOOS=linux   _GOARCH=386
    - _GOOS=linux   _GOARCH=amd64
    - _GOOS=linux   _GOARCH=arm
    - _GOOS=darwin  _GOARCH=amd64

script:
  - export GOOS=${_GOOS}
  - export GOARCH=${_GOARCH}
  - go get -v
  - go build -v

before_deploy:
  - zip httpsify-${GOOS}-${GOARCH}.zip httpsify{,.exe}

deploy:
  provider: releases
  api_key:
    secure: jH8TGNkOe8lVLl/H1mvBZRaN5Hi1iRotqtVOa6Gs4MPUaRwIYnJB3XsxeX+M5or1nWXIpJQkhxRCpcWGdzCmI1SREkfOYQB7EK7XVsqUYkQgwAE5ZYdEZD/oj12Anav42zErbibJYZTJ1bFOYHYJZoaM2wSoWKPvw2aIQvOMJVFlHAdtvp8QYZ7j+qAjRP4kXGZk40SO4cySCo1kADjpUAQS8MLK45YOc6ybe6/X464dlYkdRcABAng+dALbSnyR6YXn2CFsXNfRXRTmt64DtEibvKibeJnfLL2wZf0Xf1zGs1KnpbiSY6Sy3pHprxUStSh9IVS8I13ssS7GBMicsEVhs+yC4nwReggwB0riNDrYuw81zwWYuOHeL7zthhtpTuBiypGG6QYF6hS2jNfXV9lLtcP0O55CZyC+jDUoX029Irp5l077teTGarJJSqzGOokS193p6XUHUvdaYJp1HSGM0nfkMn8JBkk9I5b/WVMEIl1gdJ+dacsBj3OtE8/X8ioQXdMR4L5lsnGT7qBK0vanLV715bnCc9OTexRaiCMBdgu2KYI9gu/KsIQvjl/jZGgWE3c5f/RlWdw/+WHqw+0dKYOnln1OMDU6r+Dpaz200ArxK5UQgNyZDaaBrghT9DP13ds1WWzcwA1Zq6hIlV8XUdXMoz+T7GxcL9ESJpA=
  file_glob: true
  skip_cleanup: true
  file: httpsify-*.zip
  on:
    repo: scottjg/httpsify
    tags: true
